github.com:
    oauth_token: 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
    user: xbunax
    git_protocol: ssh
    users:
        xbunax:
            oauth_token: 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
